apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: aliwazeer/todo-list-nodejs:latest
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: mongo-secret
