version: '3.8'

services:
  todo-app:
    image: aliwazeer/todo-list-nodejs:latest
    container_name: todo-app
    ports:
      - "7200:3000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7200"]
      interval: 30s
      timeout: 10s
      retries: 3

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    command: --interval 60
